# Generated by Django 2.2.4 on 2019-08-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('applicant_id', models.IntegerField(db_column='Applicant_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='First_Name', max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='Middle_Name', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=50, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='Date_of_Birth', null=True)),
                ('citizenship', models.CharField(blank=True, db_column='Citizenship', max_length=50, null=True)),
                ('passport_num', models.CharField(blank=True, db_column='Passport_Num', max_length=50, null=True)),
                ('personal_id', models.CharField(blank=True, db_column='Personal_ID', max_length=50, null=True)),
                ('passport_exp_date', models.DateField(blank=True, db_column='Passport_exp_date', null=True)),
                ('photo_link', models.CharField(blank=True, db_column='Photo_link', max_length=240, null=True)),
                ('creation_date', models.DateField(blank=True, db_column='Creation_date', null=True)),
                ('last_update_date', models.DateField(blank=True, db_column='Last_update_date', null=True)),
            ],
            options={
                'db_table': 'Applicants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_id', models.IntegerField(primary_key=True, serialize=False)),
                ('free_education_flag', models.CharField(blank=True, db_column='Free_education_flag', max_length=1, null=True)),
                ('paid_education_flag', models.CharField(blank=True, db_column='Paid_education_flag', max_length=1, null=True)),
                ('full_time_education_flag', models.CharField(blank=True, db_column='Full_time_education_flag', max_length=1, null=True)),
                ('part_time_education_flag', models.CharField(blank=True, db_column='Part_time_education_flag', max_length=1, null=True)),
                ('after_9_years_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('after_11_years_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('certificate_avg', models.IntegerField(blank=True, db_column='Certificate_Avg', null=True)),
                ('number_1_test_mark', models.IntegerField(blank=True, db_column='1_Test_Mark', null=True)),
                ('number_1_test_subject_id', models.IntegerField(blank=True, db_column='1_Test_Subject_id', null=True)),
                ('number_2_test_mark', models.IntegerField(blank=True, db_column='2_Test_Mark', null=True)),
                ('number_2_test_subject_id', models.IntegerField(blank=True, db_column='2_Test_Subject_id', null=True)),
                ('admitted_flag', models.CharField(blank=True, db_column='Admitted_Flag', max_length=1, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('creation_date', models.DateField(blank=True, db_column='Creation_date', null=True)),
                ('last_update_date', models.DateField(blank=True, db_column='Last_update_date', null=True)),
                ('disable_flag', models.CharField(blank=True, db_column='Disable_flag', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, db_column='Mark', null=True)),
            ],
            options={
                'db_table': 'Certificate_Marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificate_id', models.IntegerField(db_column='Certificate_id', primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(blank=True, db_column='Certificate_type', max_length=50, null=True)),
                ('certificate_date', models.DateField(blank=True, db_column='Certificate_date', null=True)),
                ('certificate_number', models.CharField(blank=True, db_column='Certificate_number', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Certificates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('college_id', models.IntegerField(db_column='College_id', primary_key=True, serialize=False)),
                ('college_name', models.CharField(blank=True, db_column='College_name', max_length=50, null=True)),
                ('college_type', models.CharField(blank=True, db_column='College_type', max_length=50, null=True)),
                ('college_desc', models.CharField(blank=True, db_column='College_desc', max_length=150, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('disable_flag', models.CharField(blank=True, db_column='Disable_flag', max_length=1, null=True)),
                ('creation_date', models.DateField(blank=True, db_column='Creation_date', null=True)),
                ('last_update_date', models.DateField(blank=True, db_column='Last_update_date', null=True)),
            ],
            options={
                'db_table': 'Colleges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamTypes',
            fields=[
                ('exam_type_id', models.IntegerField(db_column='Exam_type_id', primary_key=True, serialize=False)),
                ('exam_type_name', models.CharField(blank=True, db_column='Exam_Type_Name', max_length=50, null=True)),
                ('exam_type_desc', models.CharField(blank=True, db_column='Exam_Type_Desc', max_length=240, null=True)),
                ('disable_flag', models.CharField(blank=True, db_column='Disable_flag', max_length=1, null=True)),
                ('creation_date', models.DateField(blank=True, db_column='Creation_date', null=True)),
                ('last_update_date', models.DateField(blank=True, db_column='Last_update_date', null=True)),
            ],
            options={
                'db_table': 'Exam_Types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('period_id', models.IntegerField(db_column='Period_ID', primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('period_type', models.CharField(blank=True, db_column='Period_type', max_length=50, null=True)),
                ('number_9_years_free_education_start_date', models.DateField(blank=True, db_column='9_years_Free_education_start_date', null=True)),
                ('number_9_years_free_education_end_date', models.DateField(blank=True, db_column='9_years_Free_education_end_date', null=True)),
                ('number_9_years_paid_education_start_date', models.DateField(blank=True, db_column='9_years_Paid_education_start_date', null=True)),
                ('number_9_years_paid_education_end_date', models.DateField(blank=True, db_column='9_years_Paid_education_end_date', null=True)),
                ('number_11_years_free_education_start_date', models.DateField(blank=True, db_column='11_years_Free_education_start_date', null=True)),
                ('number_11_years_free_education_end_date', models.DateField(blank=True, db_column='11_years_Free_education_end_date', null=True)),
                ('number_11_years_paid_education_start_date', models.DateField(blank=True, db_column='11_years_Paid_education_start_date', null=True)),
                ('number_11_years_paid_education_end_date', models.DateField(blank=True, db_column='11_years_Paid_education_end_date', null=True)),
                ('disable_flag', models.CharField(blank=True, db_column='Disable_flag', max_length=1, null=True)),
                ('creation_date', models.DateField(blank=True, db_column='Creation_date', null=True)),
                ('last_update_date', models.DateField(blank=True, db_column='Last_update_date', null=True)),
            ],
            options={
                'db_table': 'Periods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('spec_id', models.IntegerField(db_column='Spec_id', primary_key=True, serialize=False)),
                ('spec_name', models.CharField(blank=True, db_column='Spec_name', max_length=50, null=True)),
                ('spec_desc', models.CharField(blank=True, db_column='Spec_desc', max_length=255, null=True)),
                ('disable_flag', models.CharField(blank=True, db_column='Disable_flag', max_length=1, null=True)),
                ('creation_date', models.DateField(blank=True, db_column='Creation_date', null=True)),
                ('last_update_date', models.DateField(blank=True, db_column='Last_update_date', null=True)),
            ],
            options={
                'db_table': 'Specialties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('stat_id', models.IntegerField(db_column='Stat_id', primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('free_education_plan', models.IntegerField(blank=True, db_column='Free_education_plan', null=True)),
                ('free_education_passing_score', models.IntegerField(blank=True, db_column='Free_education_passing_score', null=True)),
                ('free_education_app_amt', models.IntegerField(blank=True, db_column='Free_education_app_amt', null=True)),
                ('paid_education_plan', models.IntegerField(blank=True, db_column='Paid_education_plan', null=True)),
                ('paid_education_passing_score', models.IntegerField(blank=True, db_column='Paid_education_passing_score', null=True)),
                ('paid_education_app_amt', models.IntegerField(blank=True, db_column='Paid_education_app_amt', null=True)),
                ('full_time_education_plan', models.IntegerField(blank=True, db_column='Full_time_education_plan', null=True)),
                ('full_time_education_passing_score', models.IntegerField(blank=True, db_column='Full_time_education_passing_score', null=True)),
                ('full_time_education_app_amt', models.IntegerField(blank=True, db_column='Full_time_education_app_amt', null=True)),
                ('part_time_education_plan', models.IntegerField(blank=True, db_column='Part_time_education_plan', null=True)),
                ('part_time_education_passing_score', models.IntegerField(blank=True, db_column='Part_time_education_passing score', null=True)),
                ('part_time_education_app_amt', models.IntegerField(blank=True, db_column='Part_time_education_app_amt', null=True)),
                ('number_9_year_education_plan', models.IntegerField(blank=True, db_column='9_year_education_plan', null=True)),
                ('number_9_year_education_passing_score', models.IntegerField(blank=True, db_column='9_year_education_passing_score', null=True)),
                ('number_9_year_education_app_amt', models.IntegerField(blank=True, db_column='9_year_education_app_amt', null=True)),
                ('number_11_year_education_plan', models.IntegerField(blank=True, db_column='11_year_education_plan', null=True)),
                ('number_11_year_education_passing_score', models.IntegerField(blank=True, db_column='11_year_education_passing_score', null=True)),
                ('number_11_year_education_app_amt', models.IntegerField(blank=True, db_column='11_year_education_app_amt', null=True)),
            ],
            options={
                'db_table': 'Statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectPriority',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True)),
                ('creation_date', models.DateField(blank=True, db_column='Creation_date', null=True)),
                ('last_update_date', models.DateField(blank=True, db_column='Last_update_date', null=True)),
            ],
            options={
                'db_table': 'Subject_Priority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.IntegerField(db_column='Subject_ID', primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, db_column='Subject_name', max_length=50, null=True)),
                ('subject_type', models.CharField(blank=True, db_column='Subject_type', max_length=50, null=True)),
                ('subject_desc', models.CharField(blank=True, db_column='Subject_desc', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('privilege_id', models.AutoField(db_column='Privilege_id', primary_key=True, serialize=False)),
                ('privilege_name', models.CharField(blank=True, db_column='Privilege_name', max_length=50, null=True)),
                ('privilege_desc', models.CharField(blank=True, db_column='Privilege_desc', max_length=240, null=True)),
                ('disable_flag', models.CharField(blank=True, db_column='Disable_flag', max_length=1, null=True)),
                ('creation_date', models.DateField(blank=True, db_column='Creation_date', null=True)),
                ('last_update_date', models.DateField(blank=True, db_column='Last_update_date', null=True)),
            ],
            options={
                'db_table': 'Privileges',
            },
        ),
    ]
