# Generated by Django 2.2.4 on 2019-08-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privileges',
            name='privilege_id',
            field=models.IntegerField(db_column='Privilege_id', primary_key=True, serialize=False),
        ),
    ]
