# Generated by Django 2.2.4 on 2019-08-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_id', models.IntegerField()),
                ('spec_name', models.CharField(max_length=50)),
                ('spec_desc', models.CharField(max_length=250)),
                ('colledge_id', models.IntegerField()),
                ('disable_flag', models.CharField(max_length=1)),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField()),
            ],
        ),
    ]
