# Generated by Django 2.2.4 on 2019-08-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190817_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='spec_id',
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_education_flag', models.CharField(max_length=1)),
                ('paid_education_flag', models.CharField(max_length=1)),
                ('full_time_education', models.CharField(max_length=1)),
                ('part_time_education', models.CharField(max_length=1)),
                ('after_9_years', models.CharField(max_length=1)),
                ('after_11_years', models.CharField(max_length=1)),
                ('certificate_avg', models.FloatField()),
                ('test_mark_1', models.IntegerField()),
                ('test_subject_1', models.CharField(max_length=50)),
                ('test_mark_2', models.IntegerField()),
                ('test_subject_2', models.CharField(max_length=50)),
                ('admitted_flag', models.CharField(max_length=50)),
                ('privilege_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Applicants')),
                ('spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Specialty')),
            ],
        ),
    ]
